version: '3'
services:
  api:
    build:
      context: .
      dockerfile: ./.cloud/docker/Dockerfile
    container_name: order_api
    environment:
      API_KEY: '${API_KEY}'
      AUTH_DOMAIN: '${AUTH_DOMAIN}'
      DATABASE_URL: '${DATABASE_URL}'
      STORAGE_BUCKET: '${STORAGE_BUCKET}'
      MESSAGING_SENDER_ID: '${MESSAGING_SENDER_ID}'
      APP_ID: '${APP_ID}'
      TYPE: '${TYPE}'
      PRIVATE_KEY_ID: '${PRIVATE_KEY_ID}'
      PRIVATE_KEY: '${PRIVATE_KEY}'
      CLIENT_EMAIL: '${CLIENT_EMAIL}'
      CLIENT_ID: '${CLIENT_ID}'
      AUTH_URL: '${AUTH_URL}'
      TOKEN_URI: '${TOKEN_URI}'
      AUTH_PROVIDER_X509_CERT_URL: '${AUTH_PROVIDER_X509_CERT_URL}'
      CLIENT_X509_CERT_URL: '${CLIENT_X509_CERT_URL}'
      CC_TEST_REPORTER_ID: '${CC_TEST_REPORTER_ID}'
    ports:
    - "${APP_DOCKER_PORT:-8081}:3001"
    volumes:
      - '.:/usr/src/app'
    networks:
      - order

networks:
  order:
    driver: bridge
